version: '3.8'

services:
  frontend-react:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend-nodejs
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    networks:
      - app-network
    restart: always

  backend-nodejs:
    build:
      context: ./be
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=takakazu-chat
      - BE_PORT=5000
      - FE_PORT=3000
    depends_on:
      - database-pg
    networks:
      - app-network
    volumes:
      - ./be:/usr/src/app
      - /usr/src/app/node_modules
    # command: sh -c "npm install && npm run dev" # command override --- keep commented

  database-pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: takakazu-chat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
